### PR TITLE
Optional CF Aliases

### PR DESCRIPTION
**Pull request by dantheultraman**
In preparation for CF migration, making cf aliaes optional by allowing aliases to be declared as empty list `[]`. Also introduce a switch variable `dns_aliases_enabled` to prevent route53 record from being created.

### CODE REVIEW

**Comment by dantheultraman** [comment]
Community modules no not support TF12; here is a ticket for the feature request:
https://github.com/cloudposse/terraform-aws-cloudfront-cdn/pull/29

**Comment by dantheultraman** [comment]
PR updated to support Terraform11

**Comment by pmyjavec** [comment]
@dantheultraman is the fact this is failing expected?

**Comment by pmyjavec** [comment]
I tested this, and it's ready to go. @dantheultraman I'll merged this for you.

**Comment by dantheultraman** [comment]
ACM will still be created with the alias, but as long as the  new variable `cf_aliases`  is not specified, it won't be configured in CF distribution.

**Comment by dantheultraman** [comment]
Close and merge to https://github.com/paidy/terraform-aws-static-site/pull/4/files

**Pull request closed without merging**
